config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#top"
  
  resources :posts do
    resource :favorite, only: [:create, :destroy]
    post "/", to: "comments#create", as: "comments"
    resources :comments, only: [:destroy]
    collection do
      get "search"
    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true, length: {maximum: 200}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one_attached :vision_image
  
  validates :title, presence: true, length: {maximum: 25}
  validates :vision_image, presence: true
  
  def get_vision_image(width, height)
    unless vision_image.attached?
      file_path = Rails.root.join("app/assets/images/no.jpg")
      vision_image.attach(io: File.open(file_path), filename: "no-image.jpg", content_type: "image/jpeg")
    end
    vision_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post

  def self.ransackable_attributes(auth_object = nil)
    ["name", "post_id"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {maximum: 20}, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  def set_search
    @q = Tag.ransack(params[:q])
    @results = @q.result
    # 検索でヒットした投稿のidを配列に入れる
    @post_id = []
    @results.each do |a|
      @post_id.push(a.post_id)
    end
    # 重複している投稿idを消し、降順にソートする
    @post_id = @post_id.uniq.sort.reverse
    # ソートされた投稿idを使用して投稿を取得し配列に入れる
    @post = @post_id.map { |id| Post.find(id) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    if @comment.save
      redirect_to post_path(@post)
    else
      render "posts/show"
    end
  end
  
  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_path(params[:post_id])
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_back fallback_location: root_path
  end
  
  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_back fallback_location: root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_post_user?, only: [:edit, :update]

  def top
  end
  
  def search
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.vision_image.attached?
      tags = Vision.get_image_data(post_params[:vision_image])
    else
      tags = ["none"]
    end
    if @post.save
      tags.each do |tag|
        @post.tags.create(name: tag)
      end
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    @q = Tag.ransack(params[:q])
    @posts = Post.order(id: "DESC")
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  rescue ActiveRecord::RecordNotFound #存在しない投稿ページをひらこうとした場合
    redirect_to posts_path
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :vision_image)
  end

  def is_post_user?
    @post = Post.find(params[:id])
    unless @post.user_id == current_user.id
      redirect_to post_path(@post)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_login_user?, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: "DESC")
  rescue ActiveRecord::RecordNotFound #存在しないユーザページをひらこうとした場合
    redirect_to user_path(current_user)
  end

  def index
    @users = User.all
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
end

private
def user_params
  params.require(:user).permit(:name)
end

def is_login_user?
  @user = User.find(params[:id])
  unless @user.id == current_user.id
    redirect_to user_path(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= form_with model: [post, comment], url: post_comments_path(post, anchor: "form"), id: "form" do |f| %>
  <h3>コメント</h3>
  <%= render "layouts/error", error: comment %>
  <div class="form-group mb-1">
    <%= f.text_area :comment , rows: "3", placeholder: "200文字以内", class: "form-control" %>
  </div>
  <div class="form-group text-right">
    <%= f.submit "送信", class: "btn btn-md btn-success px-5" %>
  </div>
<% end %>
<div>
  <div><i class="fa-regular fa-comment"></i> <%= post.comments.count %>件のコメント</div>
  <% post.comments.each do |post_comment| %>
    <div class="d-flex flex-column border my-2 py-2 bg-light shadow-sm">
      <div class="d-flex justify-content-between align-items-center mx-2 mb-2">
        <div style="font-size: 14px;">
          <% if post_comment.user == post.user %>
            <span class="d-block text-danger" style="font-size: 10px;">投稿者</span>
          <% end %>
          <div class="text-wrap text-break">
            <%= link_to user_path(post_comment.user), class: "text-info" do %>
              <i class="fa-solid fa-user"></i> <%= post_comment.user.name %>
            <% end %>
          </div>
        </div>
        <% if post_comment.user_id == current_user.id || post.user == current_user %>
          <%= link_to post_comment_path(post, post_comment), method: :delete, "data-confirm" => "コメントを削除しますか？", class: "text-nowrap text-danger" do %>
            <i class="fa-solid fa-trash-can fa-lg ml-1"></i>
          <% end %>
        <% end %>
      </div>
      <div class="mx-2 p-2 bg-white border rounded"><%= simple_format(post_comment.comment, class: "mb-0 text-break") %></div>
    </div>
  <% end %>
</div>

app/views/favorites/_favorite.html.erb
<% if favorite.favorited_by?(current_user) %>
  <span class="h5 text-danger m-0">
    <%= link_to "♥", post_favorite_path(favorite), method: :delete, class: "text-danger", style:"text-decoration: none;" %>
    <%= favorite.favorites.count %>
  </span>
<% else %>
  <span class="h5 m-0">
    <%= link_to "♡", post_favorite_path(favorite), method: :post, class: "text-dark", style:"text-decoration: none;" %>
    <%= favorite.favorites.count %>
  </span>
<% end %>

app/views/layouts/_error.html.erb
<% if error.errors.any? %>
  <div class="list-group list-group-item-danger p-2 my-1">
    <%= error.errors.count %>件のエラーが発生しました。
    <ul>
      <% error.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer bg-secondary text-light">
  <div class='container mt-5'>
    <div class='row align-items-center justify-content-between mx-auto py-2'>
      <a class="text-light" href="https://forms.gle/LvRJdu9RiYLmiTS47" target="_blank">
        <i class="fa-solid fa-clipboard-question"></i>
        お問い合わせ
      </a>
      <div class="mb-0">&copy; 2024 Ibuki Hirato, All rights reserved</div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-expand-lg navbar-dark bg-secondary mb-3">
  <a class="navbar-brand mr-sm-auto ml-sm-0 mx-auto pt-0" href="/">PhotoSense</a>
  <div class="d-flex mx-auto mx-sm-0 flex-grow-1">
    <% if user_signed_in? %>
      <%= search_form_for @q, url: search_posts_path, class: "form-inline flex-grow-1 flex-nowrap ml-0 ml-sm-3" do |f| %>
        <%= f.search_field :name_cont, placeholder: "検索：例）food", class: "form-control" %>
        <button type="submit" class="btn btn-dark" name="commit">
          <i class="fa-solid fa-magnifying-glass"></i>
        </button>
      <% end %>
    <% end %>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse ml-auto" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fa-solid fa-house"></i> ホーム
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user), class: "nav-link" do %>
            <i class="fa-solid fa-address-card"></i> マイページ
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_post_path, class: "nav-link" do %>
            <i class="fa-solid fa-pen-to-square"></i> 新規投稿
          <% end %>
        </li>
        <div class="dropdown nav-item">
          <button class="btn btn-secondary dropdown-toggle nav-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa-solid fa-list"></i> 一覧
          </button>
          <div class="dropdown-menu bg-light" aria-labelledby="dropdownMenuButton">
            <%= link_to posts_path, class: "nav-link dropdown-item text-secondary ml-2 ml-lg-0" do %>
              <i class="fa-solid fa-image"></i> 写真
            <% end %>
            <%= link_to users_path, class: "nav-link dropdown-item text-secondary ml-2 ml-lg-0" do %>
              <i class="fa-solid fa-users"></i> ユーザー
            <% end %>
          </div>
        </div>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            <i class="fa-solid fa-right-from-bracket"></i> ログアウト
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <i class="fa-solid fa-user-plus"></i> アカウント作成
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: "nav-link" do %>
            <i class="fa-solid fa-right-to-bracket"></i> ログイン
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSense</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4caf6c7c0f.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="footerFixed d-flex flex-column" style="min-height: 100vh;">
      <header><%= render "layouts/header" %></header>
      <main class="container">
        <%# deivseのフラッシュメッセージを表示 %>
        <% if notice %>
          <div class="alert alert-info alert-dismissible fade show text-center" role="alert">
            <span class="notice"><%= notice %></span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <% if alert %>
          <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
            <span class="alert"><%= alert %></span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        <% end %>
        <div class="row">
          <%= yield %>
        </div>
      </main>
      <footer class="mt-auto"><%= render "layouts/footer" %></footer>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="col d-flex justify-content-between flex-wrap pt-3">
  <% posts.each do |vision| %>
    <div class="card shadow mb-3 mx-auto bg-light" style="width: 300px;">
      <div class="d-flex justify-content-center align-items-center">
        <%= link_to post_path(vision) do %>
          <%= image_tag vision.get_vision_image(300, 300), class: "card-img-top img-fluid" %>
        <% end %>
      </div>
      <div class="card-body d-flex align-items-end">
        <div class="w-100">
          <h3 class="card-title text-truncate"><%= link_to "#{vision.title}", post_path(vision), class: "text-dark" %></h3>
          <hr>
          <div class="w-100 d-flex align-items-center justify-content-between flex-wrap">
            <h6 class="btn btn-info text-truncate w-50 mb-0">
              <%= link_to user_path(vision.user), class: "text-light" do %>
                <i class="fa-solid fa-user"></i>
                <%= vision.user.name %>
              <% end %>
            </h6>
            <div>
              <%= render "favorites/favorite", favorite: vision %>
              <span class="h5 ml-1">
                <%= link_to post_path(vision), class: "text-dark" do %>
                  <i class="fa-regular fa-comment"></i>
                  <%= vision.comments.count %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <!--表示時に左右の位置を揃えるため-->
  <div class="post"></div>
  <div class="post"></div>
</div>

app/views/posts/edit.html.erb
<div class="col-11 col-md-8 col-lg-5 col-xl-4 mx-auto">
  <div class="card mt-5">
    <div class="card-body">
      <h2 class="card-title text-center">タイトル編集</h2>
      <hr>
      <%= render "layouts/error", error: @post %>
      <%= form_with model: @post do |f| %>
        <div class="form-group">
          <%= f.label :title, "タイトル" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "変更", class: "btn btn-lg w-100 btn-outline-success mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h2 class="w-100 text-center">投稿一覧</h2>
<%= render "post", posts: @posts %>

app/views/posts/new.html.erb
<div class="col-11 col-md-8 col-lg-5 col-xl-4 mx-auto">
  <div class="card mt-5">
    <div class="card-body">
      <h2 class="card-title text-center">投稿</h2>
      <hr>
      <%= render "layouts/error", error: @post %>
      <%= form_with model: @post do |f| %>
        <div class="form-group">
          <div class="d-flex justify-content-between align-items-center flex-wrap mb-2">
            <%= f.label :vision_image, "画像", class: "m-0" %>
            <!-- Button trigger modal -->
            <button id="previewBtn" type="button" class="btn btn-primary btn-sm" style=" display: none;" data-toggle="modal" data-target="#imagePreview">
              画像表示 <i class="fa-solid fa-up-right-and-down-left-from-center"></i>
            </button>
            <!-- Modal -->
            <div class="modal fade" id="imagePreview" tabindex="-1" role="dialog" aria-labelledby="imagePreviewTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="imagePreviewTitle">画像のプレビュー</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <img id="preview" class="img-fluid mx-auto" style="display: none;">
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= f.file_field :vision_image, accept: "image/*", class: "form-control-file", id: "fileInput"%>
        </div>
        <div id="drop-area" class="mt-3 px-2 py-3 border rounded text-center d-none d-lg-block">
          <span>ここに画像をﾄﾞﾗｯｸﾞ&ﾄﾞﾛｯﾌﾟ</span>
        </div>
        <div class="form-group">
          <%= f.label :title, "タイトル" %><br>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "投稿", class: "btn btn-lg w-100 btn-outline-success mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<h2 class="w-100 text-center">
  <%= @post.count %>件の検索結果：
  <span>#<%= params[:q][:name_cont] %></span>
</h2>
<%= render "posts/post", posts: @post %>

app/views/posts/show.html.erb
<div class="col col-sm-11 col-lg-10 mx-auto">
  <div class="d-md-flex align-items-center mb-2 border-bottom">
    <h2 class="text-center"><%= @post.title %></h2>
    <div class="ml-auto">
      <div class="text-center">
        <%= render "favorites/favorite", favorite: @post %>
        <% if @post.user_id == current_user.id %>
          ｜
          <%= link_to "編集", edit_post_path(@post), class: "text-info" %>
          ｜
          <%= link_to "削除", post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "text-danger" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="text-center my-3">
    <%= image_tag @post.get_vision_image(600,600), class: "img-fluid" %>
  </div>
  <h3>投稿者</h3>
  <h6 class="btn btn-info">
    <%= link_to user_path(@post.user), class: "text-light" do %>
      <i class="fa-solid fa-user"></i>
      <%= @post.user.name %>
    <% end %>
  </h6>
  <h3>タグ</h3>
  <div class="list-group list-group-horizontal d-inline-flex w-100" style="overflow-x: auto;">
    <% @post.tags.each do |tag| %>
      <%= link_to "# #{tag.name}", search_posts_path(@q, :"q[name_cont]" => "#{tag.name}"), class: "badge badge-primary mx-2 p-2 h6 text-nowrap" %>
    <% end %>
  </div>
  <%= render "comments/comment", {post: @post, comment: @comment} %>
</div>

app/views/posts/top.html.erb
<div class="col-10 col-lg-6 mx-auto">
  <h1 class="mb-3">本サイトについて</h1>
  <p class="mb-2">本サイトは、画像投稿サイトです。</p>
  <p class="mb-2">投稿時に自動的にタグが生成されます。</p>
  <p class="mb-2">画面上部の検索フォームからタグ名を検索することで関連した投稿を表示することが出来ます。</p>
</div>

app/views/users/edit.html.erb
<div class="col-11 col-md-8 col-lg-5 col-xl-4 mx-auto">
  <div class="card mt-5">
    <div class="card-body">
      <h2 class="card-title text-center">プロフィール編集</h2>
      <hr>
      <%= render "layouts/error", error: @user %>
      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "ユーザ名" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "変更", class: "btn btn-lg w-100 btn-outline-success mt-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="col col-lg-10 mx-auto text-center">
  <h2>ユーザ一覧</h2>
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <th scape="col">#</th>
      <th scape="col">ユーザ名</th>
      <th scape="col">投稿数</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th scape="row" class="table-secondary">
            <%= link_to user_path(user), class: "text-dark" do %>
              <%= user.id %>
            <% end %>
          </th>
          <td class="text-left">
            <%= link_to user_path(user) do %>
              <i class="fa-solid fa-up-right-from-square mr-1"></i>
              <%= user.name %>
            <% end %>
          </td>
          <td><%= user.posts.count %> 件</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="w-100 text-center">
  <% if @user == current_user %>
    <h2>マイページ</h2>
  <% else %>
    <h2><%= @user.name %>のページ</h2>
  <% end %>
</div>
<div class="w-100 row mx-auto">
  <div class="col-sm-3 text-center mb-5 position-relative">
    <div class="sticky-top">
      <h2>プロフィール</h2>
      <table class="table table-bordered">
        <thead class="thead-light">
          <th>ユーザ名</th>
        </thead>
        <tbody>
          <tr><td><%= @user.name %></td></tr>
          <% if @user == current_user %>
            <tr>
              <td>
                <%= link_to edit_user_path(@user), class: "d-block btn btn-outline-secondary" do %>
                  <span><i class="fa-solid fa-user-pen"></i>編集</span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <thead class="thead-light">
          <th>総投稿数</th>
        </thead>
        <tbody>
          <td><%= @user.posts.count %>件</td>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-sm-9">
    <h2 class="text-center">投稿</h2>
    <%= render "posts/post", posts: @posts %>
  </div>
</div>